services:
  - type: web
    name: dota-glicko-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/main.py
    envVars:
      - key: PANDASCORE_API_KEY
        sync: false
      - key: PANDASCORE_BASE_URL
        value: https://api.pandascore.co
